// 行程模版状态枚举
export enum ItineraryStatus {
  DRAFT = 'draft',
  PUBLISHED = 'published',
  ARCHIVED = 'archived',
}

// 预算枚举
export enum Budget {
  LOW = 'low',
  MEDIUM = 'medium',
  HIGH = 'high',
  ECONOMY = 'economy',
  COMFORT = 'comfort',
  LUXURY = 'luxury',
}

// 旅行风格枚举
export enum TravelStyle {
  RELAXED = 'relaxed',
  MODERATE = 'moderate',
  ACTIVE = 'active',
  ADVENTUROUS = 'adventurous',
  INTENSIVE = 'intensive',
}

// 时段类型
export type TimeSlotType =
  | 'transport'
  | 'attraction'
  | 'meal'
  | 'hotel'
  | 'shopping'
  | 'activity'

// 坐标信息
export interface Coordinates {
  lat: number
  lng: number
}

// 名称信息
export interface NameInfo {
  chinese?: string
  english?: string
  local?: string
}

// 地址信息
export interface AddressInfo {
  chinese?: string
  english?: string
  local?: string
}

// 定价详情
export interface PricingDetail {
  detail?: string
  [key: string]: any
}

// 推荐信息
export interface RecommendationsInfo {
  visitTips?: string
  bestTimeToVisit?: string
  nearbyAttractions?: string
  visitDuration?: number
  [key: string]: any
}

// 联系方式
export interface ContactInfo {
  info?: string
  [key: string]: any
}

// 活动详情
export interface ActivityDetails {
  notes?: string
  description?: string
  name?: NameInfo
  address?: AddressInfo
  transportation?: string
  openingHours?: string
  pricing?: PricingDetail
  rating?: number
  recommendations?: RecommendationsInfo
  contact?: ContactInfo
  accessibility?: string
  category?: string
  [key: string]: any
}

// 时间段信息
export interface TimeSlot {
  id?: string
  time: string
  title?: string
  activity?: string
  type?: TimeSlotType
  coordinates?: Coordinates
  notes?: string
  details?: ActivityDetails | Record<string, any>
  cost?: number
  duration?: number
}

// 天数信息
export interface Day {
  id?: string
  day: number
  date?: string
  timeSlots: TimeSlot[]
}

// 推荐信息
export interface Recommendations {
  accommodation?: string
  transportation?: string
  food?: string
  tips?: string
  [key: string]: any
}

// 任务信息
export interface Task {
  id?: string
  title: string
  completed?: boolean
  createdAt?: number
  autoGenerated?: boolean
  autoKey?: string
  category?: string
  destination?: string
  links?: Array<{ label: string; url: string }>
}

// 行程数据
export interface ItineraryData {
  destination?: string
  duration?: number
  budget?: Budget | string
  preferences?: string[]
  travelStyle?: TravelStyle | string
  itinerary?: any[]
  recommendations?: Recommendations
  days: Day[]
  totalCost?: number
  summary?: string
  title: string
}

// 完整的行程模版
export interface ItineraryTemplate {
  id: string
  status?: ItineraryStatus | string
  language?: string
  itineraryData: ItineraryData
  tasks?: Task[]
  createdBy?: string | null
  updatedBy?: string | null
  createdAt: string
  updatedAt: string
}

// 查询参数
export interface ItineraryQueryParams {
  status?: ItineraryStatus | 'all' // draft/published/archived，传 all 或不传表示全部
  keyword?: string // 关键字搜索（标题或摘要）
  language?: string // zh-CN/en-US
  destination?: string // 目的地
  budget?: Budget | 'all' | string // low/medium/high/economy/comfort/luxury，传 all 或不传表示全部
  travelStyle?: TravelStyle | 'all' | string // relaxed/moderate/active/adventurous/intensive，传 all 或不传表示全部
  page?: number // 页码，默认 1，从 1 开始
  limit?: number // 每页数量，默认 10，最大 100
}

// 列表响应
export interface ItineraryListResponse {
  data: ItineraryTemplate[]
  total: number
  page: number
  limit: number
}

// 创建/更新表单数据（请求体格式，字段在顶层）
export interface ItineraryFormData {
  title: string // 必填
  destination?: string
  duration?: number // 1-30
  budget?: Budget | string // low/medium/high/economy/comfort/luxury
  preferences?: string[]
  travelStyle?: TravelStyle | string // relaxed/moderate/active/adventurous/intensive
  recommendations?: Recommendations
  days?: Day[]
  totalCost?: number
  summary?: string
  status?: ItineraryStatus | string // draft/published/archived，默认 draft
  language?: string // zh-CN/en-US，默认 zh-CN
  tasks?: Task[]
}

// API 响应基础结构
export interface ApiResponse<T> {
  success?: boolean
  data?: T
  message?: string
}

